# Generated by Django 3.0.5 on 2020-07-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
